#!/bin/bash
# Selfie Script

sudo instagram-scraper selfie --tag --login-user michaelcuneouon --login-pass M0bean0e75! --retry-forever --maximum 25000 -t image --latest -d selfie |
sudo inotifywait -m -e moved_to selfie --format "%w%f" --excludei '(part)' |
  while read filename;
   do
    echo Scraped File: "$filename";
    convert -rotate "180" "$filename" printed/selfie.jpg;
    lpr -P ZJ-58 -o brightness=250 printed/selfie.jpg;
    rm "$filename";
  done
