#!/bin/bash
# run_instagram_scraper
# 
# Instagram scraper for Ralph Kenke Portrait Prize
#

sudo instagram-scraper selfie --tag --login-user michaelcuneouon --login-pass M0bean0e75! --retry-forever --maximum 100 -t image --latest -d selfie
